### ISSUE TITLE
Tooltips need attributes changed to something with full columns

### ISSUE THREAD

**Issue by kchapinriddle** [g-simmons/infovisfinal#8]
Right now they're showing 0 for many datapoints because those points have empty cells.

**Comment by kchapinriddle** [comment]
Same for the parallel plot too, since they're set with the same attributes right now.

**Comment by kchapinriddle** [comment]
Upon examination of the columns we have _no_ full columns for nutritional information.  
Gabe, is merging columns a possibility, or do I need to start adding logic to handle blanks?

**Comment by g-simmons** [comment]
Merged the columns for the macronutrients, and updated the attributes in the visualizations. The data still needs more cleaning for micronutrients, vitamins, etc but Fat, Protein, Carbs, and Fiber should each have around 90% completeness. 

For the remaining incomplete values, I think leaving them in is ok, as it reflects the nature of the dataset and preserves our dataset size. For now, 10% incomplete is not bad and it could go either way. But when we start to visualize the micronutrients/compounds, this issue will become more important, since there will be a lot of missing data. Dropping rows with missing data will reduce the dataset size significantly. 

Open to input on this, we can play around with it.

**Comment by g-simmons** [comment]
I'll leave this open for now, @kchapinriddle can close if you feel like the issue is resolved.

**Comment by kchapinriddle** [comment]
This is a massive improvement, thank you!  
I'll close this, we're basically at full columns at this point for what we're displaying and if micronutrients pose a problem we'll just open a new one.
